language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to run tests
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - cd tests
  - python test.py
